### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MarlikAlmighty** [Gskartwii/roblox-dissector#68]
![изображение](https://user-images.githubusercontent.com/17222940/105230242-1ca86a80-5b76-11eb-90cf-d48ae14c9448.png)

**Comment by expected-ingot** [comment]
Had the same issue, but fixed it. Do you have the GTK3 runtime installed? If not then download it here: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases
